crds:
  install: true
  keep: true

configs:
  params:
    server.insecure: true

server:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.olympus.local
    path: /
    pathType: Prefix